/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'olive-deep': 'var(--olive-deep)',
        olive: 'var(--olive)',
        'olive-light': 'var(--olive-light)',
        'olive-glow': 'var(--olive-glow)',
        sand: 'var(--sand)',
        'sand-light': 'var(--sand-light)',
        'sand-warm': 'var(--sand-warm)',
        cream: 'var(--cream)',
        'warm-white': 'var(--warm-white)',
        bronze: 'var(--bronze)',
        'bronze-light': 'var(--bronze-light)',
        sunset: 'var(--sunset)',
        'sunset-deep': 'var(--sunset-deep)',
        shadow: 'var(--shadow)',
        'shadow-soft': 'var(--shadow-soft)',
        'glow-olive': 'var(--glow-olive)',
        'glow-sand': 'var(--glow-sand)',
        'glow-sunset': 'var(--glow-sunset)',
      },
      fontFamily: {
        ar: 'var(--font-ar)',
        en: 'var(--font-en)',
      },
      transitionTimingFunction: {
        cinematic: 'var(--ease-cinematic)',
        smooth: 'var(--ease-smooth)',
        expo: 'var(--ease-expo)',
        elastic: 'var(--ease-elastic)',
      },
      keyframes: {
        loaderPulse: {
          '0%, 100%': { opacity: '0.3', transform: 'scale(1)' },
          '50%': { opacity: '0.7', transform: 'scale(1.05)' },
        },
        loaderChar: {
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        loaderLine: {
          '0%, 100%': { opacity: '0.3', transform: 'scaleX(0.5)' },
          '50%': { opacity: '1', transform: 'scaleX(1)' },
        },
        lightRaySway: {
          '0%, 100%': { opacity: '0.3', transform: 'rotate(calc(var(--i) * 3deg - 5deg))' },
          '50%': { opacity: '0.6', transform: 'rotate(calc(var(--i) * 3deg + 5deg))' },
        },
        leafFloat: {
          '0%, 100%': { transform: 'translate(0, 0) rotate(0deg)' },
          '25%': { transform: 'translate(30px, -20px) rotate(45deg)' },
          '50%': { transform: 'translate(-20px, -40px) rotate(90deg)' },
          '75%': { transform: 'translate(40px, -10px) rotate(135deg)' },
        },
        palmSwayRight: {
          '0%, 100%': { transform: 'rotate(0deg) translateX(0)' },
          '33%': { transform: 'rotate(1.5deg) translateX(8px)' },
          '66%': { transform: 'rotate(-0.8deg) translateX(-4px)' },
        },
        palmSwayLeft: {
          '0%, 100%': { transform: 'rotate(0deg) translateX(0)' },
          '40%': { transform: 'rotate(-1.2deg) translateX(-6px)' },
          '70%': { transform: 'rotate(0.6deg) translateX(3px)' },
        },
        leafSway: {
          '0%, 100%': { transform: 'rotate(0deg)' },
          '50%': { transform: 'rotate(2deg)' },
        },
        birdFly1: {
          '0%': { left: '-5%', transform: 'translateY(0) scaleX(1)' },
          '45%': { left: '105%', transform: 'translateY(-10px) scaleX(1)' },
          '50%': { left: '105%', transform: 'translateY(-10px) scaleX(-1)' },
          '95%': { left: '-5%', transform: 'translateY(5px) scaleX(-1)' },
          '100%': { left: '-5%', transform: 'translateY(0) scaleX(1)' },
        },
        birdFly2: {
          '0%': { right: '-5%', transform: 'translateY(0) scaleX(-1)' },
          '45%': { right: '105%', transform: 'translateY(15px) scaleX(-1)' },
          '50%': { right: '105%', transform: 'translateY(15px) scaleX(1)' },
          '95%': { right: '-5%', transform: 'translateY(-5px) scaleX(1)' },
          '100%': { right: '-5%', transform: 'translateY(0) scaleX(-1)' },
        },
        birdFly3: {
          '0%': { left: '-5%', transform: 'translateY(0) scaleX(1)' },
          '48%': { left: '105%', transform: 'translateY(-20px) scaleX(1)' },
          '50%': { left: '105%', transform: 'translateY(-20px) scaleX(-1)' },
          '98%': { left: '-5%', transform: 'translateY(10px) scaleX(-1)' },
          '100%': { left: '-5%', transform: 'translateY(0) scaleX(1)' },
        },
        duneBreath: {
          '0%, 100%': { transform: 'translateY(0) scaleX(1)' },
          '50%': { transform: 'translateY(-5px) scaleX(1.01)' },
        },
        sandDrift1: {
          '0%, 100%': { transform: 'translateX(0) scaleY(1)' },
          '33%': { transform: 'translateX(-2%) scaleY(1.04)' },
          '66%': { transform: 'translateX(1.5%) scaleY(0.98)' },
        },
        sandDrift2: {
          '0%, 100%': { transform: 'translateX(0) scaleY(1)' },
          '40%': { transform: 'translateX(2%) scaleY(1.05)' },
          '70%': { transform: 'translateX(-1%) scaleY(0.97)' },
        },
        sandDrift3: {
          '0%, 100%': { transform: 'translateX(0) scaleY(1)' },
          '25%': { transform: 'translateX(-1.5%) scaleY(1.03)' },
          '50%': { transform: 'translateX(1%) scaleY(0.99)' },
          '75%': { transform: 'translateX(-0.5%) scaleY(1.02)' },
        },
        fadeInUp: {
          from: { opacity: '0', transform: 'translateY(30px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        scrollPulse: {
          '0%, 100%': { opacity: '0.3', transform: 'scaleY(0.6)' },
          '50%': { opacity: '0.8', transform: 'scaleY(1)' },
        },
        glowPulse: {
          '0%, 100%': { opacity: '0.5', transform: 'translate(-50%, -50%) scale(1)' },
          '50%': { opacity: '0.8', transform: 'translate(-50%, -50%) scale(1.1)' },
        },
        orbPulse: {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.5' },
          '50%': { transform: 'scale(1.1)', opacity: '0.8' },
        },
        shineSweep: {
          '0%': { transform: 'translateX(-100%) rotate(0deg)' },
          '100%': { transform: 'translateX(100%) rotate(0deg)' },
        },
        dotPulse: {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.3' },
          '50%': { transform: 'scale(1.3)', opacity: '0.1' },
        },
        circleSpin: {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
      },
      animation: {
        loaderPulse: 'loaderPulse 2s ease-in-out infinite',
        loaderChar: 'loaderChar 0.6s var(--ease-cinematic) forwards',
        loaderLine: 'loaderLine 1.5s ease-in-out infinite',
        lightRaySway: 'lightRaySway 8s ease-in-out infinite',
        leafFloat: 'leafFloat 20s ease-in-out infinite',
        palmSwayRight: 'palmSwayRight 7s ease-in-out infinite',
        palmSwayLeft: 'palmSwayLeft 8s ease-in-out infinite',
        leafSway: 'leafSway 4s ease-in-out infinite',
        birdFly1: 'birdFly1 30s linear infinite',
        birdFly2: 'birdFly2 40s linear infinite 5s',
        birdFly3: 'birdFly3 35s linear infinite 12s',
        duneBreath: 'duneBreath 10s ease-in-out infinite',
        sandDrift1: 'sandDrift1 18s ease-in-out infinite',
        sandDrift2: 'sandDrift2 14s ease-in-out infinite',
        sandDrift3: 'sandDrift3 10s ease-in-out infinite',
        fadeInUp: 'fadeInUp 1s var(--ease-cinematic) forwards',
        scrollPulse: 'scrollPulse 2s ease-in-out infinite',
        glowPulse: 'glowPulse 6s ease-in-out infinite',
        orbPulse: 'orbPulse 4s ease-in-out infinite',
        shineSweep: 'shineSweep 5s ease-in-out infinite',
        dotPulse: 'dotPulse 3s ease-in-out infinite',
        circleSpin: 'circleSpin 60s linear infinite',
      },
    },
  },
  plugins: [],
};
